# Generated by Django 5.1.2 on 2024-12-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='type',
            field=models.CharField(default='car', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
