# Generated by Django 5.1.2 on 2024-12-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historypage', '0002_remove_bookinghistory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='car_number',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
