# Generated by Django 5.1.2 on 2024-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('landmark', models.CharField(max_length=255, verbose_name='Landmark')),
            ],
        ),
    ]
