# Generated by Django 5.1.2 on 2024-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('days', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(null=True, upload_to='vehicle_items/')),
            ],
        ),
    ]
