# Generated by Django 5.1.2 on 2024-12-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='days',
        ),
    ]
