# Generated by Django 5.1.2 on 2024-12-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpage', '0002_remove_vehicle_date_remove_vehicle_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='Car', max_length=200),
        ),
    ]
