# Generated by Django 5.1.2 on 2024-12-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpage', '0003_vehicle_book_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_number',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
